server:
  port: 8001 # 端口号
  servlet:
    context-path: /image # 应用的上下文路径

spring:
  application:
    name: focason-image # 应用名称
  rabbitmq:
    host: {RABBITMQ_HOST:localhost} # RabbitMQ主机名
    port: {RABBITMQ_PORT:5672} # RabbitMQ端口
    username: {RABBITMQ_USERNAME:guest} # RabbitMQ用户名
    password: {RABBITMQ_PASSWORD:guest} # RabbitMQ密码
security:
  oauth2:
    client:
      #不多说了
      client-id: web
      client-secret: 654321
      #Token获取地址
      access-token-uri: http://localhost:9000/sso/oauth/token
      #验证页面地址
      user-authorization-uri: http://localhost:9000/sso/oauth/authorize
    resource:
      #Token信息获取和校验地址
      token-info-uri: http://localhost:9000/sso/oauth/check_token

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh # 为Actuator开放所需监控地址

# 日志级别
logging:
  level:
    root: INFO
