server:
  port: 9000
  servlet:
    context-path: /auth

spring:
  application:
    name: focason-oauth2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:focason}?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.jdbc.Driver
    #druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:focason}?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:password}
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
  jackson:
    time-zone: Asia/Tokyo
  freemarker:
    check-template-location: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: off

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

# JWTトークン
jwt:
  secret: ${APP_SECRET:iWpJnu21sTumTsfyldkfjpo23iiu34tierfjwerjfop43oeorgfsndhfopoewkrjti43orweksdnfjw4e}
  access_token_expires_in: 1200 # 単位：秒
  refresh_token_expires_in: 604800 # 単位：秒
  refresh_token_header: X-REFRESH-TOKEN
auth:
  name: admin

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh