server:
  port: 8081 # 端口号
  servlet:
    context-path: /users # 应用的上下文路径

#security:
#  basic:
#    enabled: false

spring:
  application:
    name: focason-user # 应用名称
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
    allow-circular-references: true
  rabbitmq:
    host: {RABBITMQ_HOST:localhost} # RabbitMQ主机名
    port: {RABBITMQ_PORT:5672} # RabbitMQ端口
    username: {RABBITMQ_USERNAME:guest} # RabbitMQ用户名
    password: {RABBITMQ_PASSWORD:guest} # RabbitMQ密码
  jackson:
    time-zone: Asia/Tokyo
  freemarker:
    check-template-location: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: off

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh # 为Actuator开放所需监控地址

# ログ
logging:
  level:
    root: INFO

# AWS
cloud:
  aws:
    region: {AWS_REGION:ap-northeast-1}
    s3:
      file-upload:
        bucket-name: {AWS_S3_BUCKET_NAME:focason-sandbox}
        prefix:
        pre-signed-url-valid-minutes: 15 # PreSigned连接的有效时间，单位：分钟

# Doma
#doma:
#  dialect: mysql

foo: 777777