server:
  port: 9000 # 端口号
  servlet:
    context-path: /sso # 应用的上下文路径

spring:
  application:
    name: focason-oauth2 # 应用名称
  rabbitmq:
    host: {RABBITMQ_HOST:localhost} # RabbitMQ主机名
    port: {RABBITMQ_PORT:5672} # RabbitMQ端口
    username: {RABBITMQ_USERNAME:guest} # RabbitMQ用户名
    password: {RABBITMQ_PASSWORD:guest} # RabbitMQ密码
  jackson:
    time-zone: Asia/Tokyo

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh # 为Actuator开放所需监控地址

# 日志级别
logging:
  level:
    root: INFO

# JWTトークン
jwt:
  secret: ${APP_SECRET:iWpJnu21sTumTsfyldkfjpo23iiu34tierfjwerjfop43oeorgfsndhfopoewkrjti43orweksdnfjw4e}
  access_token_expires_in: 1200 # 単位：秒
  refresh_token_expires_in: 604800 # 単位：秒
  refresh_token_header: X-REFRESH-TOKEN
