server:
  port: 8001 # 端口号
  servlet:
    context-path: /image # 应用的上下文路径

spring:
  application:
    name: focason-image # 应用名称
  rabbitmq:
    host: {RABBITMQ_HOST:localhost} # RabbitMQ主机名
    port: {RABBITMQ_PORT:5672} # RabbitMQ端口
    username: {RABBITMQ_USERNAME:guest} # RabbitMQ用户名
    password: {RABBITMQ_PASSWORD:guest} # RabbitMQ密码

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh # 为Actuator开放所需监控地址

# 日志级别
logging:
  level:
    root: INFO
