server:
  port: 8080

spring:
  application:
    name: focason-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    allow-circular-references: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        - id: focason-oauth2
          uri: lb://focason-oauth2
          predicates:
            - Path=/auth/**
        - id: focason-user
          uri: lb://focason-user
          predicates:
            - Path=/users/**
#  security:
#    user:
#      name: root
#      password: password
#  datasource:
#    #druid连接池
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:focason}?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
#      username: ${DB_USERNAME:root}
#      password: ${DB_PASSWORD:password}
#      web-stat-filter:
#        enabled: true
#      stat-view-servlet:
#        enabled: true
#        login-username: admin
#        login-password: 123456
#        reset-enable: false

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
