server:
  port: 8080

spring:
  application:
    name: focason-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    allow-circular-references: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      routes:
        - id: focason-oauth2
          uri: lb://focason-oauth2
          predicates:
            - Path=/auth/**
        - id: focason-user
          uri: lb://focason-user
          predicates:
            - Path=/users/**

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
