server:
  port: 8081 # 端口号

spring:
  application:
    name: focason-user # 应用名称
  main:
    web-application-type: reactive # 程序类型
    allow-bean-definition-overriding: true
    allow-circular-references: true # 允许cloud:
  rabbitmq:
    host: {RABBITMQ_HOST:localhost} # RabbitMQ主机名
    port: {RABBITMQ_PORT:5672} # RabbitMQ端口
    username: {RABBITMQ_USERNAME:guest} # RabbitMQ用户名
    password: {RABBITMQ_PASSWORD:guest} # RabbitMQ密码
  datasource:
    # 数据库连接信息
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:focason}?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.jdbc.Driver
    #druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:focason}?useSSL=false&autoReconnect=true&characterEncoding=UTF-8&useUnicode=yes
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:password}
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
  jackson:
    time-zone: Asia/Tokyo
  freemarker:
    check-template-location: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: off

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh # 为Actuator开放所需监控地址

# ログ
logging:
  level:
    root: INFO

# AWS
cloud:
  aws:
    region: {AWS_REGION:ap-northeast-1}
    s3:
      file-upload:
        bucket-name: {AWS_S3_BUCKET_NAME:focason-sandbox}
        prefix:
        pre-signed-url-valid-minutes: 15 # PreSigned连接的有效时间，单位：分钟

# Doma
#doma:
#  dialect: mysql
