server:
  port: 8080 # 端口号

spring:
  application:
    name: focason-gateway # 应用名称
  main:
    web-application-type: reactive # 程序类型
    allow-bean-definition-overriding: true
    allow-circular-references: true # 允许
  rabbitmq:
    host: {RABBITMQ_HOST:localhost} # RabbitMQ主机名
    port: {RABBITMQ_PORT:5672} # RabbitMQ端口
    username: {RABBITMQ_USERNAME:guest} # RabbitMQ用户名
    password: {RABBITMQ_PASSWORD:guest} # RabbitMQ密码
  security:
    oauth2:
      client:
        provider:
          cognito:
            issuerUri: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_66Rm8XNOz
            user-name-attribute: username
        registration:
          cognito:
            client-id: ekotpetmo0dkckfesb5sm9bq2 # focason-cognito-client
            client-secret: cr2qpd1rkdmhnm6lkja5sj1e9b9tg1v436hr5qrp3l7053l4uo7
            client-name: focason-cognito-client
            provider: cognito
            scope: openid
            redirect-uri: 'http://localhost:8080/api/cognito/callback'
            authorization-grant-type: authorization_code

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh # 为Actuator开放所需监控地址

# 日志级别
logging:
  level:
    root: INFO

# JWTトークン
jwt:
  secret: ${APP_SECRET:iWpJnu21sTumTsfyldkfjpo23iiu34tierfjwerjfop43oeorgfsndhfopoewkrjti43orweksdnfjw4e}
  access_token_expires_in: 1200 # 単位：秒
  refresh_token_expires_in: 604800 # 単位：秒
  refresh_token_header: X-REFRESH-TOKEN
